config/routes.rb
Rails.application.routes.draw do
  root 'top#index'
  get 'term', to: 'top#term'
  get 'privacy', to: 'top#privacy'
  get 'spot_edit_select', to: 'spots#edit_select'
  get 'users/account'
  resources :top, only: [:index]
  resources :spots do
    collection do
      get 'search'
    end
    resources :comments, only: [:index, :create]
    resource :likes, only: [:create, :destroy]
  end
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    post 'users/guest_login', to: 'users/sessions#guest_login'
    get 'users/likes'
    get 'users', to: redirect('users/sign_up')
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :spot

  validates :content, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :spot
end

app/models/spot.rb
class Spot < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many_attached :images
  MAX_IMAGES_COUNT = 4
  MAX_IMAGE_SIZE = 10

  def liked?(user)
    likes.exists?(user_id: user.id)
  end

  validates :name, length: { in: 1..25 }
  validates :address, length: { in: 1..30 }
  validates :images, content_type: {
    in: ['image/jpeg', 'image/jpg', 'image/gif', 'image/png'],
    message: "の対応ファイルは jpeg、jpg、gif、png です",
  }
  validates :images, size: { less_than: MAX_IMAGE_SIZE.megabytes, message: "ファイルのサイズは1枚につき#{MAX_IMAGE_SIZE}MBまでです" }
  validates :images, limit: { max: MAX_IMAGES_COUNT, message: "をアップロードできるのは#{MAX_IMAGES_COUNT}枚までです" }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :spots, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_one_attached :avatar
  devise :database_authenticatable, :registerable, :rememberable, :validatable
  MAX_IMAGE_SIZE = 10

  def self.guest
    find_or_create_by!(email: 'guest@email.com') do |user|
      user.nickname = "ゲストユーザー"
      user.introduction = "ゲストユーザーです。"
      user.password = SecureRandom.urlsafe_base64
    end
  end

  validates :nickname, presence: true
  validates :email, presence: true
  validates :avatar, content_type: {
    in: ['image/jpeg', 'image/jpg', 'image/gif', 'image/png'],
    message: "の対応ファイルは jpeg、jpg、gif、png です",
  }
  validates :avatar, size: { less_than: MAX_IMAGE_SIZE.megabytes, message: "ファイルのサイズは#{MAX_IMAGE_SIZE}MBまでです" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :search
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def search
    @q = Spot.ransack(params[:q])
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :introduction, :avatar])
    devise_parameter_sanitizer.permit(:account_update, keys: [:nickname, :introduction, :avatar])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @spot = Spot.with_attached_images.find(params[:spot_id])
    @comments = @spot.comments.eager_load(:user).all.order(created_at: :desc)
  end

  def create
    @comment = current_user.comments.new(comment_params)
    if @comment.save
      flash[:notice] = "コメントを投稿しました"
      redirect_back(fallback_location: root_path)
    else
      flash[:alert] = "コメントが未入力のため投稿できませんでした"
      redirect_back(fallback_location: root_path)
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :spot_id)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @spot = Spot.find(params[:spot_id])
    like = current_user.likes.new(spot_id: params[:spot_id])
    like.save
  end

  def destroy
    @spot = Spot.find(params[:spot_id])
    like = current_user.likes.find_by(spot_id: params[:spot_id])
    like.destroy
  end
end

app/controllers/spots_controller.rb
class SpotsController < ApplicationController
  before_action :set_spot, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:create, :update, :destroy]

  def index
    @spots = Spot.with_attached_images
    @spots = @q.result

    if @q.name_or_address_or_feature_or_describe_cont.presence
      @search_word = @q.name_or_address_or_feature_or_describe_cont
    elsif @q.address_cont.presence
      @search_address = @q.address_cont
    end
  end

  def show
    @comments = @spot.comments.eager_load(:user).order(created_at: :desc)
    if current_user.present?
      @comment = current_user.comments.new
    end
  end

  def new
    @spot = Spot.new
  end

  def edit
  end

  def create
    @spot = Spot.new(spot_params)
    respond_to do |format|
      if @spot.save
        format.html { redirect_to spot_url(@spot), notice: "おすすめスポットの投稿が完了しました" }
        format.json { render :show, status: :created, location: @spot }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @spot.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @spot.update(spot_params)
        format.html { redirect_to spot_url(@spot), notice: "おすすめスポットの編集が完了しました" }
        format.json { render :show, status: :ok, location: @spot }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @spot.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @spot.destroy
    respond_to do |format|
      format.html { redirect_to spots_url, notice: "おすすめスポットの削除が完了しました" }
      format.json { head :no_content }
    end
  end

  def edit_select
    @myspots = Spot.with_attached_images.where(user_id: current_user.id) if current_user.present?
  end

  private

  def set_spot
    @spot = Spot.with_attached_images.includes(:user).find(params[:id])
  end

  def spot_params
    params.require(:spot).permit(:user_id, :name, :address, :feature, :describe, images: [])
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :ensure_normal_user, only: [:update, :destroy]

  def ensure_normal_user
    if resource.email == 'guest@email.com'
      redirect_to root_path, alert: 'ゲストユーザーの更新・削除はできません'
    end
  end

  def update
    super
    if account_update_params[:avatar].present?
      resource.avatar.attach(account_update_params[:avatar])
    end
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def guest_login
    user = User.guest
    sign_in user
    redirect_to root_path, notice: "ゲストユーザーとしてログインしました"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def likes
    if current_user.present?
      likes = Like.where(user_id: current_user.id).pluck(:spot_id)
      @like_list = Spot.with_attached_images.find(likes)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  BASE_TITLE = "ItteMiyo".freeze

  def full_title(page_title)
    page_title.blank? ? BASE_TITLE : "#{page_title} - #{BASE_TITLE}"
  end
end

app/views/comments/index.html.erb
<%= render 'shared/page_title', page_title: @spot.name + "の全てのコメント" %>
<div class="container">
  <div class="row" data-turbolinks="false">
    <div class="col">
      <div class="font18-26 font-m-700 py-2 py-md-3"><i class="fa-regular fa-comment"></i>&nbsp;全てのコメント</div>
      <div class="d-flex mb-3">
        <div>
          <% if @spot.images.attached? %>
            <%= image_tag @spot.images.first.variant(resize: "800x600", gravity: "center", crop: "700x520+0+0", quality: 80).processed, class: "max100" %>
          <% else %>
            <%= image_tag asset_path('sample.jpg'), class: "card-img-top spot-thumb", alt: "Spot photo" %>
          <% end%>
        </div>
        <div class="d-flex align-items-center ms-3 width68">
          <span class="font18-26 nowrap"><%= @spot.name %></span>
        </div>
      </div>
      <% if @comments.present? %>
        <% @comments.each do |comment| %>
          <div class="col border rounded-3 mb-3 px-3 py-1">
            <span class="font14"><%= comment.user.nickname %>さんのコメント</span>
            <div class="font14-16"><%= simple_format(comment.content, class: "my-1") %></div>
            <span class="font14">コメント日時: <%= l comment.created_at %></span>
          </div>
        <% end %>
      <% else %>
        <div class="col border my-3 p-2">
          <span class="font14">まだコメントが投稿されていません</span>
        </div>
      <% end %>
      <%= link_to "戻る", spot_path(@spot), class: "d-block mb-3 ms-1 text-black" %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag 'favicon.ico' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'https://fonts.googleapis.com/css2?family=Kosugi+Maru&family=M+PLUS+Rounded+1c:wght@400;500;700&display=swap', media: "all" %>
  </head>
  <body class="font-k">
    <%= render 'shared/header' %>
    <%= yield %>
    <%= render 'shared/footer' %>
    <%= render 'shared/mobilemenu' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/8cfa2fd524.js" crossorigin="anonymous"></script>
  </body>
</html>

app/views/likes/_likes.html.erb
<% if spot.liked?(current_user) %>
  <p class="spot-option-show mb-1 me-1 me-sm-2 d-inline-block">
    <%= link_to spot_likes_path(spot), method: :delete, class: "text-black nondeco", remote: true do %>
      <i class="fa-solid fa-heart" style="color: #FF2F40;"></i>&nbsp;&nbsp;<%= spot.likes.length %>
    <% end %>
  </p>
<% else %>
  <p class="spot-option-show mb-1 me-1 me-sm-2 d-inline-block">
    <%= link_to spot_likes_path(spot), method: :post, class: "text-black nondeco", remote: true do %>
      <i class="fa-regular fa-heart"></i>&nbsp;&nbsp;<%= spot.likes.length %>
    <% end %>
  </p>
<% end %>

app/views/shared/_footer.html.erb
<div id="footer" class="container-fluid px-0">
  <div class="row gx-0" data-turbolinks="false">
    <ul class="nav justify-content-center py-4 text-center lh-1" style="background-color: #DFDFDD;">
      <li class="nav-item col-12 col-md-auto mx-auto">
        <%= link_to "利用規約", term_path, class: "nav-link text-body normallink" %>
      </li>
      <!-- <li class="nav-item col-12 col-md-auto mx-auto">
        <a class="nav-link text-body normallink" href="#">サイトマップ</a>
      </li>
      <li class="nav-item col-12 col-md-auto mx-auto">
        <a class="nav-link text-body normallink" href="#">お問い合わせ</a>
      </li> -->
      <li class="nav-item col-12 col-md-auto mx-auto">
        <%= link_to "プライバシーポリシー", privacy_path, class: "nav-link text-body normallink" %>
      </li>
    </ul>
    <div class="p-4 bg-black text-center">
      <p class="small" style="color: #C09565;">&copy; 2022-<%= Time.current.year %> Copyright ItteMiyo inc.</p>
    </div>
  </div>
</div>

app/views/shared/_header.html.erb
<div class="top-space"></div>
<nav class="navbar navbar-expand-md navbar-light bg-white fixed-top underborder" data-turbolinks="false">
  <div class="container-fluid mx-md-3">
    <div class="col col-md-5 me-sm-2 headerheight">
      <%= link_to root_path do %>
        <%= image_tag 'banner.png', alt: "banner", class: "img-fluid", style: "max-height: 70px;" %>
      <% end %>
    </div>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-between" id="navbarSupportedContent">
      <div class="col">
        <%= search_form_for @q, class: "d-flex homeform" do |f| %>
          <%= f.search_field :name_or_address_or_feature_or_describe_cont, class: "form-control searchform", placeholder: "フリーワード検索" %>
          <%= f.submit "検索", class: "btn btn-dark searchbutton" %>
        <% end %>
      </div>
      <div class="col d-flex justify-content-end ms-sm-2">
        <nav class="navbar">
          <% if user_signed_in? %>
            <div class="dropdown">
              <% if current_user.avatar.attached? %>
                <%= link_to image_tag(current_user.avatar.variant(resize: "200x200", gravity: "center", crop: "200x200+0+0", quality: 70).processed), '#', class: "dropdown-toggle hoveropacity avatar", role: "button", "data-bs-toggle": "dropdown", "aria-expanded": "false" %>
              <% else %>
                <%= link_to image_tag('sampleavatar.jpg'), '#', class: "dropdown-toggle hoveropacity avatar", role: "button", "data-bs-toggle": "dropdown", "aria-expanded": "false" %>
              <% end %>
              <ul class="dropdown-menu dropdown-menu-end font-m-400" style="min-width: 200px;">
                <li><span class="dropdown-item-text" style="pointer-events: none;"><span class="font-m-500"><%= current_user.nickname %></span> さん</span></li>
                <li><hr class="dropdown-divider"></li>
                <li><%= link_to "おすすめスポット一覧", spots_path, class: "dropdown-item" %></li>
                <li><%= link_to "いいね！したスポット一覧", users_likes_path, class: "dropdown-item" %></li>
                <li><%= link_to "おすすめスポット新規投稿", new_spot_path, class: "dropdown-item" %></li>
                <li><%= link_to "投稿したスポットの編集", spot_edit_select_path, class: "dropdown-item" %></li>
                <li><hr class="dropdown-divider"></li>
                <li><%= link_to "マイページ", users_account_path, class: "dropdown-item" %></li>
                <li><%= link_to "アカウント設定", edit_user_registration_path, class: "dropdown-item" %></li>
                <li><hr class="dropdown-divider"></li>
                <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "dropdown-item nondeco" %></li>
              </ul>
            </div>
          <% else %>
            <div class="dropdown">
              <%= link_to image_tag('nonlogin.png'), '#', class: "dropdown-toggle hoveropacity nonlogin", role: "button", "data-bs-toggle": "dropdown", "aria-expanded": "false" %>
              <ul class="dropdown-menu dropdown-menu-end font-m-400">
                <li><%= link_to "ログイン", new_user_session_path, class: "dropdown-item font-m-500" %></li>
                <li><%= link_to "ユーザー登録", new_user_registration_path, class: "dropdown-item" %></li>
                <li><hr class="dropdown-divider"></li>
                <li><%= link_to "スポット一覧を見てみる", spots_path, class: "dropdown-item" %></li>
              </ul>
            </div>
          <% end %>
        </nav>
      </div>
    </div>
  </div>
</nav>
<%= render 'shared/flash' %>

app/views/shared/_mobilemenu.html.erb
<div class="bottom-space d-block d-md-none"></div>
<div class="d-block d-md-none container-fluid text-center fixed-bottom py-0 bg-white">
  <div class="row fs10 mobilemenu" data-turbolinks="false">
    <div class="col">
      <%= link_to root_path, class: "nondeco text-black" do %>
        <div><%= image_tag asset_path('home.jpg'), size: '30x30' %></div>
        <div>トップページ</div>
      <% end %>
    </div>
    <div class="col">
      <div class="dropup">
        <span class="dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
          <div><%= image_tag asset_path('spot.png'), size: '30x30' %></div>
          <div>スポットメニュー</div>
        </span>
        <ul class="dropdown-menu font-m-400">
          <% if user_signed_in? %>
            <li><%= link_to "スポットを編集", spot_edit_select_path, class: "dropdown-item" %></li>
            <li><%= link_to "スポットを投稿", new_spot_path, class: "dropdown-item" %></li>
            <li><hr class="dropdown-divider"></li>
            <li><%= link_to "いいね！一覧へ", users_likes_path, class: "dropdown-item" %></li>
            <li><%= link_to "スポット一覧へ", spots_path, class: "dropdown-item" %></li>
          <% else %>
            <li><%= link_to "スポット一覧へ", spots_path, class: "dropdown-item" %></li>
          <% end %>
        </ul>
      </div>
    </div>
    <div class="col">
      <div class="dropup">
        <span class="dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
          <div><%= image_tag asset_path('user.png'), size: '30x30' %></div>
          <div>ユーザーメニュー</div>
        </span>
        <ul class="dropdown-menu font-m-400">
          <% if user_signed_in? %>
            <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "dropdown-item" %></li>
            <li><hr class="dropdown-divider"></li>
            <li><%= link_to "アカウント設定", edit_user_registration_path, class: "dropdown-item" %></li>
            <li><%= link_to "マイページ", users_account_path, class: "dropdown-item" %></li>
          <% else %>
            <li><%= link_to "ユーザー登録", new_user_registration_path, class: "dropdown-item" %></li>
            <li><%= link_to "ログイン", new_user_session_path, class: "dropdown-item font-m-500" %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/shared/_page_title.html.erb
<% provide(:title, page_title) %>

app/views/spots/edit_select.html.erb
<%= render 'shared/page_title', page_title: "編集するスポットを選択" %>
<div class="container-fluid" data-turbolinks="false">
  <% if current_user.present? %>
    <div class="pt-3 text-center ps-md-5 pt-md-4 text-md-start font-m-700">
      <% if @myspots.present? %>
        <span class="font18-26">編集するスポットを選択して下さい</span>
      <% else %>
        <div class="font18-26">まだスポットを投稿していません</div>
        <div class="my-3"><%= link_to "スポットを投稿する", new_spot_path, class: "text-black font-m-500" %></div>
      <% end %>
    </div>
    <div class="row mb-3 mx-2">
      <% if @myspots.present? %>
        <% @myspots.each do |myspot| %>
          <div class="col-12 col-md-6 col-lg-4 col-xl-3 p-3 p-md-4 d-flex justify-content-center">
            <%= link_to edit_spot_path(myspot), class: "nondeco overhidden" do %>
              <div class="card w-100 nonebutton">
                <% if myspot.images.attached? %>
                  <%= image_tag myspot.images.first.variant(resize: "800x600!", gravity: "center", crop: "690x430+0+0", quality: 70).processed, class: "card-img-top spot-thumb" %>
                <% else %>
                  <%= image_tag asset_path('sample.jpg'), class: "card-img-top spot-thumb", alt: "Spot photo" %>
                <% end%>
                <div class="card-body px-1 py-2">
                  <h5 class="card-title spot-text-main font-m-500 mb-1"><%= myspot.name %></h5>
                  <p class="card-text spot-address font-m-400 mb-1"><%= myspot.address %></p>
                  <p class="card-text spot-describe spot-text-sub font-m-400 lh-sm pe-3 pb-1"><%= myspot.describe %></p>
                </div>
              </div>
            <% end %>
          </div>
        <% end %>
      <% end %>
    </div>
  <% else %>
    <%= render 'shared/nologin' %>
  <% end %>
</div>

app/views/spots/show.html.erb
<%= render 'shared/page_title', page_title: @spot.name %>
<%= render 'shared/spotmenu' %>
<div class="container-fluid" data-turbolinks="false">
  <div class="row justify-content-center font-m-400">
    <div class="col-md-11 my-4 px-4" style="background-color:white; max-width:1100px;">
      <h1 class="mb-0 font18-26"><%= @spot.name %></h1>
      <div class="row gx-0 justify-content-end">
        <div class="col-12 col-md-6">
          <p class="spot-address-show mb-0 d-inline-block font11-16"><%= @spot.address %></p>
        </div>
        <div class="col-6 d-flex justify-content-end font14-18">
          <div data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title="コメント">
            <p class="spot-option-show mb-1 me-3 me-sm-4 d-inline-block">
              <i class="fa-regular fa-comment"></i>&nbsp;&nbsp;<%= @comments.length %>
            </p>
          </div>
          <% if current_user.present? %>
            <div class="d-none d-lg-inline-block" id="likes_button" data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title="いいね！">
              <%= render 'likes/likes', spot: @spot %>
            </div>
            <div class="d-inline-block d-lg-none" id="likes_button_mobile">
              <%= render 'likes/likes', spot: @spot %>
            </div>
          <% else %>
            <div data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title="いいね！">
              <p class="spot-option-show mb-1 me-1 me-sm-2 d-inline-block">
                <i class="fa-regular fa-heart"></i>&nbsp;&nbsp;<%= @spot.likes.length %>
              </p>
            </div>
          <% end %>
        </div>
      </div>
      <% if @spot.images.attached? %>
        <div class="container-fluid mb-3 px-0">
          <div class="row flex-row">
            <div id="carousel" class="carousel slide carousel-fade col-10 pe-0 pe-sm-3" data-bs-ride="carousel">
              <div class="carousel-inner">
                <% @spot.images.each_with_index do |image, index| %>
                  <div class="carousel-item <%= "active" if index.zero? %>" data-thumb="<%= index %>">
                    <%= image_tag image.variant(resize: "800x600", gravity: "center", crop: "700x520+0+0", quality: 80).processed, class: "w-100" %>
                  </div>
                <% end %>
              </div>
            </div>
            <div id="thumbcarousel" class="col carousel slide d-flex flex-column justify-content-center" data-interval="false">
              <% @spot.images.each_with_index do |image, index| %>
                <%= image_tag image.variant(resize: "800x600", gravity: "center", crop: "700x520+0+0", quality: 80).processed, class: "w-100 my-2", "data-bs-target": "#carousel", "data-bs-slide-to": "#{index}" %>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
      <div class="container-fluid px-0">
        <div class="row gx-0">
          <div class="col-lg-8 pe-lg-3">
            <div class="row gx-0">
              <div class="col-10 pe-0 pb-3 border-bottom">
                <p class="font-m-500 mb-0 font15-24"><%= @spot.user.nickname %>さんのおすすめスポット</p>
                <span class="font12-17"><%= @spot.address %></span>
              </div>
              <div class="col-2 d-flex justify-content-end pb-3 border-bottom">
                <% if @spot.user.avatar.present? %>
                  <%= image_tag @spot.user.avatar.variant(resize: "200x200", gravity: "center", crop: "200x200+0+0", quality: 70).processed, class: "spotavatar" %>
                <% else %>
                  <%= image_tag asset_path('sampleavatar.jpg'), class: "spotavatar" %>
                <% end %>
              </div>
              <div class="col-12 border-bottom pt-3 pb-4 font12-17">
                <span class="font-m-500">スポットの特徴<br>
                  <% if @spot.feature.present? %>
                    <%= @spot.feature %>
                  <% else %>
                    記入されていません
                  <% end %>
                </span>
              </div>
              <div class="col-12 border-bottom py-3 font11-16 minh150 mb-4">
                <span>スポットの説明<br>
                  <% if @spot.describe.present? %>
                    <%= simple_format(@spot.describe, class: "mb-2") %>
                  <% else %>
                    記入されていません
                  <% end %>
                </span>
              </div>
            </div>
          </div>
          <div class="col-lg-4 mt-lg-3 ps-lg-3">
            <% if current_user.present? %>
              <div class="d-flex justify-content-between mb-3 font14-16">
                <div><i class="fa-regular fa-comment"></i>&nbsp;コメント&nbsp;(<%= @comments.length %>)</div>
                <div class="me-2"><span class="pointer" data-bs-toggle="modal" data-bs-target="#commentModal"><u>コメントする</u></span></div>
              </div>
            <% else %>
              <div class="font14-16"><i class="fa-regular fa-comment"></i>&nbsp;コメント&nbsp;(<%= @comments.length %>)</div>
              <div class="ms-1 mb-2 font12">コメントする場合はログインが必要です。</div>
            <% end %>
            <% if @comments.present? %>
              <% @comments.first(3).each do |comment| %>
                <div class="col border rounded mb-3 px-2">
                  <span class="font14"><%= comment.user.nickname %>さんのコメント</span>
                  <div class="font14-16"><%= comment.content %></div>
                  <span class="font14">コメント日時: <%= l comment.created_at %></span>
                </div>
              <% end %>
              <div class="font14 text-end pe-1 mt--07">
                <%= link_to "全てのコメントを見る", spot_comments_path(@spot), class: "text-black" if @comments.length > 3 %>
              </div>
            <% else %>
              <div class="col border my-3 p-2">
                <span class="font14">まだコメントが投稿されていません</span>
              </div>
            <% end %>
          </div>
        </div>
        <div class="row gx-0">
          <div class="col-lg-8 pe-lg-3 font14-16">
            <%= link_to "スポット一覧に戻る", spots_path, class: "d-block text-black" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="modal fade" id="commentModal" tabindex="-1" aria-labelledby="commentModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="commentModalLabel">コメントを投稿する</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <% if current_user.present? %>
        <%= form_with(model: [@spot, @comment], method: :post) do |f| %>
          <div class="modal-body">
            <div class="mb-3">
              <%= f.text_area :content, class: "form-control minh150", placeholder: "コメントを入力して下さい&#13;&#10;改行は全てのコメントページのみ反映されます".html_safe, required: true %>
              <%= f.hidden_field :spot_id, value: @spot.id %>
            </div>
          </div>
          <div class="modal-footer justify-content-center">
            <button type="button" class="btn btn-secondary me-4" data-bs-dismiss="modal">キャンセル</button>
            <%= f.submit "投稿する", class: "btn btn-dark ms-4" %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>